enum MRPCs
{
	RPC_CLIENT_REQUEST_AUTOWALK = 1000,
	RPC_CLIENT_INCREASE_STATS,
	RPC_CLIENT_REQUEST_SUICIDE,
	RPC_SERVER_ASK_SPAWN_LOCATION,
	RPC_CLIENT_SEND_SPAWN_LOCATION,
	
	RPC_BR_SEND_CLIENT_MSG,
	RPC_BR_SEND_GLOBAL_MSG,
	RPC_BR_SET_INPUT,
	RPC_BR_FADE_IN,
	RPC_BR_FADE_OUT
}
