//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WinServInstaller.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WinServInstaller.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;endpoint&quot;: &quot;https://dayzbr.dev&quot;,
        ///    &quot;api_key&quot;: &quot;##APIKEY##&quot;
        ///}.
        /// </summary>
        internal static string API_Settings {
            get {
                return ResourceManager.GetString("API_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///set &quot;ServerName=##SERVERNAME##&quot;
        ///set &quot;ServerPath=##SERVERPATH##&quot;
        ///
        ///title %ServerName%
        ///
        ///:restart
        ///cls
        ///echo &quot;+ Updating DayZ Server&quot;
        ///call UPDATE_SERVER.bat
        ///
        ///echo &quot;+ Starting DayZ Server&quot;
        ///title %ServerName% - Online
        ///start /WAIT DayZServer_x64.exe &quot;-config=%ServerPath%\serverDZ.cfg&quot; -port=##PORT## &quot;-profiles=%ServerPath%\profiles&quot; -doLogs &quot;-mod=%ServerPath%\@CF;%ServerPath%\@Community-Online-Tools;%ServerPath%\@DayZ-Expansion-Licensed;%ServerPath%\@DayZ-Expansion;%ServerPath%\@BattleRoyale&quot;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RUN_DAYZBR {
            get {
                return ResourceManager.GetString("RUN_DAYZBR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;query_port&quot;: ##QUERYPORT##,
        ///    &quot;ip_address&quot;: &quot;##IPADDR##&quot;
        ///}.
        /// </summary>
        internal static string Server_Settings {
            get {
                return ResourceManager.GetString("Server_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @echo off
        ///
        ///set &quot;SteamCMDPath=##STEAMCMD##&quot;
        ///set &quot;ServerPath=##SERVERPATH##&quot;
        ///set &quot;WorkshopSubpath=steamapps\workshop\content\221100&quot;
        ///set &quot;GitMissionPath=##GITLABPATH##\Missions\BattleRoyale.ChernarusPlusGloom&quot;
        ///
        ///REM workshop ids for mods
        ///set &quot;CF_workshop_id=1559212036&quot;
        ///set &quot;COT_workshop_id=1564026768&quot;
        ///set &quot;Expansion_workshop_id=2116151222&quot;
        ///set &quot;Expansion_licensed_workshop_id=2116157322&quot;
        ///set &quot;BR_workshop_id=2160516972&quot;
        ///
        ///%SteamCMDPath%\steamcmd ^
        /// +login ##STEAMUSER## ##STEAMPASS## ^
        /// +force_inst [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UPDATE_SERVER {
            get {
                return ResourceManager.GetString("UPDATE_SERVER", resourceCulture);
            }
        }
    }
}
