#ifdef SERVER
/**
 *  Battle Royale - persistence for last_match.json.
 *
 *  The summary outlives the process on purpose, and unlike the leaderboard that is not an
 *  optimisation - it is the entire feature. This server restarts between every match, so the lobby a
 *  player reconnects into is the only place a summary can reach the WINNER, who is kicked fifteen
 *  seconds after winning, as well as everyone who died.
 *
 *  ONE WRITE, at match end, and that is a correctness decision rather than a performance one.
 *
 *  The tempting alternative is the leaderboard's debounced mid-match flush. It does not transfer.
 *  The served copy of the previous match lives in RAM, so overwriting the file cannot break a READ -
 *  but it makes the file do two jobs with opposite lifetimes: "the completed previous match" and "a
 *  crash journal of the current one". The first mid-match flush would replace a good match N-1 with
 *  a partial match N whose still-living players carry br_position = groups remaining at that moment
 *  rather than a finishing place, so every survivor in it reads as having placed 4th - and match N-1
 *  would be unrecoverable, because the same flush cycle overwrote the backup. The leaderboard can
 *  afford that trade because its ladder is cumulative across months; this is one cosmetic match that
 *  is regenerated by playing another.
 *
 *  Writing once buys two more things. m_Previous becomes immutable for the whole process lifetime,
 *  which is what makes serving it trivially safe - no sequence number, no invalidation, no
 *  reader/writer question. And the copy-aside becomes a free one-deep history, because at the
 *  instant of the write the primary file still holds the PREVIOUS match.
 *
 *  Nothing in here logs through BattleRoyaleUtils.Error, and that is deliberate: Error routes to
 *  the engine's Error2() and raises a Virtual Machine Exception. It is a *fatal* logger. Killing the
 *  server over a corrupt cosmetic file is the exact opposite of what this class is for.
 */
class BattleRoyaleLastMatchStore
{
    /**
     *  Read last_match.json, or NULL when there is nothing usable.
     *
     *  Everything off disk is untrusted: an operator may have hand-edited it, and a previous process
     *  may have been killed mid-write. Repair what can be repaired, drop what cannot, and never let
     *  either stop the server booting.
     */
    static BattleRoyaleLastMatchFile Load()
    {
        ref BattleRoyaleLastMatchFile store = NULL;

        if (!FileExist(BATTLEROYALE_LASTMATCH_FILE))
        {
            //--- Deliberately does NOT fall back to the backup. A missing primary is either first
            //--- boot or an operator clearing it on purpose, and silently resurrecting the match
            //--- before last from .bak would be the wrong answer to both.
            BattleRoyaleUtils.Info("[LastMatch] No last_match.json yet - no previous match to show");
            return NULL;
        }

        store = ParseSummaryFile(BATTLEROYALE_LASTMATCH_FILE);
        if (!store)
        {
            BattleRoyaleUtils.Warn("[LastMatch] last_match.json unreadable, trying the backup");
            store = ParseSummaryFile(BATTLEROYALE_LASTMATCH_BACKUP);
        }

        if (!store)
        {
            BattleRoyaleUtils.Warn("[LastMatch] Neither last_match.json nor its backup could be read");
            return NULL;
        }

        if (!store.rows)
        {
            BattleRoyaleUtils.Warn("[LastMatch] last_match.json has no rows array");
            return NULL;
        }

        Prune(store);

        string line = "[LastMatch] loaded " + store.rows.Count() + " rows";
        line = line + " winner=" + store.winner_name;
        line = line + " field=" + store.field_size;
        line = line + " grouped=" + store.grouped;
        BattleRoyaleUtils.Info(line);

        return store;
    }

    /**
     *  Write the finished match.
     *
     *  Called exactly once per process, from 9_BattleRoyaleRestart.Activate(). That state is the
     *  guaranteed end point: it is reached by every match end including "everyone rage-quit", it runs
     *  AFTER KickWinner has booked the winners' rows, and it sits a full ten seconds ahead of
     *  RequestExit.
     */
    static void Save(BattleRoyaleLastMatchFile store)
    {
        string error_message = "";

        if (!store)
            return;
        if (!store.rows)
            return;

        store.version = BR_LASTMATCH_FILE_VERSION;
        store.saved_at = BattleRoyaleTime.NowSeconds();

        //--- JsonFileLoader.SaveFile is not atomic, so the previous file is copied aside first. Here
        //--- that copy is also the one-deep history described in the class header.
        if (FileExist(BATTLEROYALE_LASTMATCH_FILE))
            CopyFile(BATTLEROYALE_LASTMATCH_FILE, BATTLEROYALE_LASTMATCH_BACKUP);

        if (!JsonFileLoader<BattleRoyaleLastMatchFile>.SaveFile(BATTLEROYALE_LASTMATCH_FILE, store, error_message))
        {
            BattleRoyaleUtils.Warn("[LastMatch] Failed to write last_match.json: " + error_message);
            return;
        }

        string line = "[LastMatch] wrote " + store.rows.Count() + " rows";
        line = line + " winner=" + store.winner_name;
        line = line + " field=" + store.field_size;
        line = line + " grouped=" + store.grouped;
        BattleRoyaleUtils.Info(line);
    }

    /**
     *  Drop rows with no uid, drop duplicates keeping the first, and cap the total.
     *
     *  The cap is applied on READ as well as on write, because the file may have been produced by a
     *  different build or edited by hand, and the row count decides the size of an RPC payload that
     *  has no chunking behind it.
     */
    private static void Prune(BattleRoyaleLastMatchFile store)
    {
        ref set<string> seen = new set<string>();
        int i = 0;

        for (i = store.rows.Count() - 1; i >= 0; i--)
        {
            BattleRoyaleLastMatchRow row = store.rows.Get(i);

            if (!row)
            {
                store.rows.RemoveOrdered(i);
                continue;
            }

            if (row.uid == "")
                store.rows.RemoveOrdered(i);
        }

        //--- Forwards, so "first occurrence wins" means the first in file order.
        for (i = 0; i < store.rows.Count(); i++)
        {
            string uid = store.rows.Get(i).uid;

            if (seen.Find(uid) >= 0)
            {
                store.rows.RemoveOrdered(i);
                i--;
                continue;
            }

            seen.Insert(uid);
        }

        while (store.rows.Count() > BR_LASTMATCH_MAX_ROWS)
            store.rows.RemoveOrdered(store.rows.Count() - 1);
    }

    /**
     *  Parse one file, or NULL.
     *
     *  NOT named ReadFile. That is a vanilla global proto in ensystem.c, and an unqualified call to a
     *  member sharing a vanilla global's name resolves to the wrong thing in EnfusionScript -
     *  BattleRoyaleLeaderboardStore carries the same warning for the same reason.
     */
    private static BattleRoyaleLastMatchFile ParseSummaryFile(string path)
    {
        ref BattleRoyaleLastMatchFile store = NULL;
        string error_message = "";

        if (!FileExist(path))
            return NULL;

        store = new BattleRoyaleLastMatchFile();

        if (!JsonFileLoader<BattleRoyaleLastMatchFile>.LoadFile(path, store, error_message))
        {
            BattleRoyaleUtils.Warn("[LastMatch] " + path + " could not be read: " + error_message);
            return NULL;
        }

        return store;
    }
}
#endif
